server:
  port: 8080
  servlet:
    context-path: /foundation

spring:
  profiles:
    active: dev   # Mặc định chạy môi trường dev, đổi sang prod khi deploy

---

# Cấu hình DEV
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlserver://localhost\DEV:1433;databaseName=WebNotesSystem;encrypt=false;trustServerCertificate=true
    username: sa
    password: root
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update       # Hibernate sẽ tạo bảng nếu chưa có, thêm cột nếu cần
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_schema: dbo   # Set schema đúng với DB
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: c8780cd2aa9a87
    password: 31095747db9c5d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false

# Gemini AI Configuration
gemini:
  api:
    key: AIzaSyBuRDi7qjcR8FwbWscejFR4YxsF9v0y8Js
    base-url: https://generativelanguage.googleapis.com/v1beta

---

# Cấu hình PROD
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:sqlserver://localhost\DEV:1433;databaseName=WebNotesSystem;encrypt=false;trustServerCertificate=true
    username: sa
    password: root
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none          # Không tạo bảng mới, chỉ dùng bảng có sẵn
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: dbo
    show-sql: false
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: c8780cd2aa9a87
    password: 31095747db9c5d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
